### ISSUE TITLE
Can I use html tag in createChatBotMessage()?

### ISSUE THREAD

**Issue by Pinni05** [FredrikOseberg/react-chatbot-kit#100]
I want to add an image in  createChatBotMessage(). Is this possible?

**Comment by FredrikOseberg** [comment]
> I want to add an image in createChatBotMessage(). Is this possible?

Yeah, you can do this with either a [widget](https://fredrikoseberg.github.io/react-chatbot-kit-docs/docs/advanced/widgets) or a [custom message](https://fredrikoseberg.github.io/react-chatbot-kit-docs/docs/advanced/custom-messages)
