### ISSUE TITLE
Changing the bot initial message dynamically

### ISSUE THREAD

**Issue by shubham-vEngageAi** [FredrikOseberg/react-chatbot-kit#107]
Hi FredrikOseberg,
I want to change the bot initial message dynamically. But I am unable to do that. please can you tell me the way to do that?
This requirement is very important for us .

Thanks and regards
Shubham Kumar

**Comment by FredrikOseberg** [comment]
> Hi FredrikOseberg, I want to change the bot initial message dynamically. But I am unable to do that. please can you tell me the way to do that? This requirement is very important for us .
> 
> Thanks and regards Shubham Kumar

You could wrap the config in a function, and provide the initial message as a parameter to that function: 

```getConfig = (message) => ({ initialMessages: [createChatBotMessage(message)] })```

**Comment by skmainwal** [comment]
config.js
---------------------
![image](https://user-images.githubusercontent.com/61382724/170975151-c0d756f6-3b08-4042-a19c-f310adc91808.png)


I want to pass the Data from APP.js 

![image](https://user-images.githubusercontent.com/61382724/170975323-6a71df33-51ac-442d-afe7-f1f882e729e9.png)

**Comment by pompy** [comment]
You can add as many dynamic messages as possible - even via rest api
Just make config dynamic ;-)

 const botinitconfig = {
    botid: 111,
    botheader: 'Pompy Bot',
    startertext: 'Welcome',
    botMessageBox: '#376B7E',
    chatButton:'#5ccc9d',
    initialMessages: init()
  }

  const init = () => {
    var initMessages = ['Welcome', 'Pompy', 'Dynamic Init Message Works'];
    return (
      initMessages.map(function (message, index) {
        return createChatBotMessage(message)
      }))
  }

<Route path="/" element={<ChatBotPage botinit={botinitconfig} />}/>
