### ISSUE TITLE
Feature request: Need timestamp for messages

### ISSUE THREAD

**Issue by ToJen** [FredrikOseberg/react-chatbot-kit#139]
I would like to use the timestamp of each message for both type `bot` and `user` however these are the only attributes that I see in `messages` in the state when I inspect it:

```json
{
  "delay": undefined,
  "id": 123,
  "loading": false,
  "message": "...",
  "type": "bot|user"
}
```

It would be helpful to have the full UTC timestamp (in the user's timezone) for both the bot and user messages.

**Comment by ToJen** [comment]
Keeping track of it myself in the payload of the options sent to `createChatbotMessage`.

**Comment by waseemdilsherim** [comment]
what about user message timestamp?

**Comment by ToJen** [comment]
@waseemdilsherim I don't remember what I did but you can get the timestamp with `new Date()` or similar just before you handle the user's message.
