### ISSUE TITLE
saveMessages doesn't work

### ISSUE THREAD

**Issue by jhonatan-dev** [FredrikOseberg/react-chatbot-kit#146]
Thanks for this great kit for making easy to build chatbot.

This is great one. But, I think, this has also some gaps. For example, to save dialogue, I tried to use saveMessages. But, it doesn't work.
And the loading component shows after getting server response. Sometimes, the server response could be 1 or even 2 secs. So, it's critical. 

I hope these gaps are get rid of asap

**Comment by jhonatan-dev** [comment]
Hi @FredrikOseberg,

I found saveMessage solution by adding few lines on useChatbot.ts script.

```
const [messageContainer, setMessageContainer] = useState({});

const setMessageContainerRef = (containerRef) => {
    setMessageContainer(containerRef)
}

useEffect(() => {
    return () => {
      if (saveMessages && typeof saveMessages === 'function') {
        const HTML = messageContainer?.current?.innerHTML.toString();
        
        if (!messageContainer) return;
        saveMessages(messagesRef.current, HTML);
      }
    };
  }, [messageContainer.current]);
```

That works fine.

May I send PR with this change?

Thanks.

**Comment by tech-alpinist** [comment]
Thanks @jhonatan-dev 
That really works well. I solved the saving messages issue.
