### ISSUE TITLE
Widget :  Unexpected Token '<' Error

### ISSUE THREAD

**Issue by Rohan-Hazari** [FredrikOseberg/react-chatbot-kit#153]
I followed the recent docs and tried to to the DogPicture widget but I kept getting this error Unexpected Token '<' at the widgetFunc line 
![image](https://github.com/FredrikOseberg/react-chatbot-kit/assets/91898040/7b6052aa-34c8-4c0b-a15e-4d6a9503a8ee)
![image](https://github.com/FredrikOseberg/react-chatbot-kit/assets/91898040/287f40f4-9210-473c-ab93-51535b57d742)

I dont understand What I did wrong

this is my config file (also showing my directory just in case )
![image](https://github.com/FredrikOseberg/react-chatbot-kit/assets/91898040/35511059-5eb1-49fb-bce1-ebe728f8a03a)

**Comment by void-ness** [comment]
Facing the same error. However adding something like below works. but this won't pass down any props

```javascript
widgets: [
        {
            widgetName: 'dogPicture',
            widgetFunc: (props) => DogPicture,
        },
    ],
```

**Comment by Rohan-Hazari** [comment]
Thanks @void-ness that worked

**Comment by void-ness** [comment]
@Rohan-Hazari I noticed the above error only while instantiating a react app using vite. I tried instantiating a react app using "create-react-app" template and the above error wasn't seen. 

Therefore it has something to do with one of the dependencies by vite.

**Comment by 0x41head** [comment]
For anyone who comes across this issue in the future. You may use something like this to pass props in Vite.
```
widgets: [
        {
            widgetName: 'dogPicture',
            widgetFunc: (props) => DogPicture(props),
        },
    ],
```
