### ISSUE TITLE
No action on button click / submit

### ISSUE THREAD

**Issue by pichlerpa** [FredrikOseberg/react-chatbot-kit#155]
Hi everyone, first of all, congrats to this great open-source project. During my first tests, I encountered the issue of not being able to send messages, it seems like there is no action behind the button or submit element, nothing happens on pressing enter or clicking the button, also no error is shown:

![image](https://github.com/FredrikOseberg/react-chatbot-kit/assets/35483858/2bd2a222-8cd0-4fea-81cf-a49c6331cbdd)

Are you familiar with this problem or could you give me a hint where/how to poke around? 

Thanks, Patrick

**Comment by hexiaogou** [comment]
Perhaps, you didn't write const parse in MessageParser.

**Comment by pichlerpa** [comment]
@hexiaogou thanks for your response, I meanwhile found another component to use.
