### ISSUE TITLE
Continue with the evolution of the react-chatbot-kit library please

### ISSUE THREAD

**Issue by matt-balda** [FredrikOseberg/react-chatbot-kit#159]

**Comment by tech-alpinist** [comment]
I am going to maintain react-chatbot module.

[@techawesome/react-chatbot](https://www.npmjs.com/package/@techawesome/react-chatbot)

Open to any good ideas and contributors

**Comment by FredrikOseberg** [comment]
@tech-alpinist 

Thanks for your interest in the project. I am amazed by the response from the community I have received over the last couple of years. 

Unfortunately, after I joined the largest open source feature flagging project in the world, the time I have to dedicate here has been limited. I would like to keep building here in the future, but right now I don't have enough time.

You are, of course, free to take this code, maintain it, extend it, redistribute and sell it. But taking the work and passing it off as your own without keeping the original licence is not ok. Currently you are in violation of the licence.

Maintaining a fork is of course ok, but be fair and keep the licence as is. Dont pass off other peoples work as your own.

**Comment by tech-alpinist** [comment]
@FredrikOseberg, 
Thanks for your response. your response is so fast.
You know why I wrote down that on your repo issue community? People want to update for a long time. All issues are very simple ones. I didn't mean to say people the repo is my own. I want users use working and completed module as they want.
Even though you never consider and check right pull requests, I did like that.
I also like this repo and thanks for your contribution to Open source community.
But if you're open other people to contribute to your repo to maintain (if you're busy or lazy), you can invite me as contributor and I will maintain this repo. Of course, will delete the forked module.
Thanks

**Comment by FredrikOseberg** [comment]
> You know why I wrote down that on your repo issue community? People want to update for a long time. All issues are very simple ones. I didn't mean to say people the repo is my own. I want users use working and completed module as they want.

Your copy of the library explicitly changed the licence to be copyrighted under your name: https://github.com/tech-alpinist/react-chatbot/blob/main/LICENSE. Was that unintentional?

Nevertheless, thank you for your interest in maintaining, but I am not interested in collaborating with people who outright insult me. Like I said, you are free to fork the library and maintain your own fork, but what you've done here is bad form in my opinion.

**Comment by tech-alpinist** [comment]
people can use  node module from my fork? you don't want to maintain the repo at all?

**Comment by FredrikOseberg** [comment]
> people can use node module from my fork? you don't want to maintain the repo at all?

It's open source. You are free to fork and maintain a different version, as long as you give credit. I already have an additional maintainer @tirsoh, and I'll look for more in the future. Thank you.

**Comment by tech-alpinist** [comment]
I saw you opened issue to find maintainer. glad to see that. if you're ok, may I am the developer to maintain this library.
will remove all my github and node module. you know, the license file is generated one while npm init for publishing to npmjs.
please let me know your thoughts
Thanks

**Comment by matt-balda** [comment]
@tech-alpinist  could you just mention the copyright of the MIT license, in your new library titled react-chatbot. We library users need evolution, improvements to bugs/flaws. I believe that we should not be selfish with codes because this goes against free/open software. However, all work must be duly honored, so I ask @tech-alpinist  to follow the copyright mention in the license.

Main improvements:

- Saving dialogue messages

- Something easier and more intuitive to deal with ActionProvider

- Something simpler to deal with Options

- Improvements to the quiz, making the quiz work like a real quiz

- Payloads improve

- Synchronization with objects and dates outside the dialogs

**Comment by tech-alpinist** [comment]
@matt-balda, do you think it's ok if the new module just contains his MIT license?
I just fixed some issues on his source. So, I agree with the module should be maintained by his honor. But, I also agree we should not be selfish. How long will it take to check PR in your opinion? I removed my cloned module. If he will maintain in the future, that's ok. But, if he doesn't, I think developer should not be confused by using this bug keeping and not maintaining module.
