### ISSUE TITLE
How can I resize of this chatbot windows?

### ISSUE THREAD

**Issue by ChrisDongWooKim** [FredrikOseberg/react-chatbot-kit#18]
@FredrikOseberg,
Hi, Thxs for providing this awesome chatbot kit in advance.
I want to resize of chatbot window size. but I couldn't find information about resizing in your documents.
I have tried to set the chatbot container's width and height in CSS files. Of course, the chatbot app didn't change its size at all.
I guessed I could have changed the size of the window using config.customStyles properties but I couldn't.
Please, Could you let me know how to change it?

**Comment by FredrikOseberg** [comment]
You should be able to change the css grabbing the chatbots css classes (inspect element in the browser) and using them in your App.css file.

**Comment by vivekshah-zymr** [comment]
@ChrisDongWooKim Did you have a better way for this?

**Comment by koiker** [comment]
I did solve the issue by creating a file called `App.css` with the folowing content:

```
.react-chatbot-kit-chat-container {
    position: relative;
    width: 100% !important;
}

.react-chatbot-kit-chat-bot-message {
    width: auto !important;
}
```

Import the css file in your index.js with:
`import ./App.css';`

**Comment by MarcoYesNo** [comment]
Anyone know how to reduce the height of the chatbot to instead of full screen, just half of the size of my screen please?
