### ISSUE TITLE
Change the avatar (even just to a different letter?)

### ISSUE THREAD

**Issue by the1andonlycj** [FredrikOseberg/react-chatbot-kit#2]
I really love this chatbot, and I took some time to get familiar with the commands and how it works, but I'd really love to be able to change the B to something else. Even just to be able to change that letter to match the name of the bot I intend to have, or (ideally) to be able to put an image in that position. Is there any way to do that?

**Comment by FredrikOseberg** [comment]
Thanks for the feedback!

Yes, you can make your own bot avatar and provide it in the config to swap out the default avatar. Check the customComponents property of this config : https://gist.github.com/FredrikOseberg/87795296efb67fe76fa05fc839d22e25
