### ISSUE TITLE
Clickable widgets

### ISSUE THREAD

**Issue by Stijnvhd** [FredrikOseberg/react-chatbot-kit#21]
Thank you for creating a great chatbot kit! Only issue I seem to have is when I add custom widgets, these aren't always clickable or only clickable in certain locations in the chatbot environment. Is there a specific reason for that?

**Comment by FredrikOseberg** [comment]
Hi! 

I'm not sure what you are referring too. What in your widget is not clickable? Since widgets are just regular react components, they _should_ follow the same rules when transformed into HTML. Can you please provide me with an example of your issue?

**Comment by Stijnvhd** [comment]
So if I render as a response a widget consisting out of 2 buttons, the buttons are only clickable in a certain area (generally the top left corner of the button) and if I arrange them in a certain way (they have to appear on top of each other but not next to each other). I also rendered a questionnaire in the chatbot and the first 3 rows aren't clickable, after those three I can do everything without any problem.

**Comment by Stijnvhd** [comment]
This is one example of a widget I call:

const example = (props) => {

    return (
        <div className="container">
            <button
                className="A"
                onClick={props.actionProvider.handleA}
            >
                A 
            </button>
            <br />
            <button
                className="B"
                onClick={props.actionProvider.handleB}
            >
                B
            </button>
            <br />
            <button
                className="C"
                onClick={props.actionProvider.handleC}
            >
                C
            </button>
        </div>
    );

**Comment by FredrikOseberg** [comment]
Do you have your code on github?

ons. 3. feb. 2021 kl. 18:40 skrev Stijnvhd <notifications@github.com>:

**Comment by Stijnvhd** [comment]
I shared an invite with you to the repository, thanks a lot for taking the time!

**Comment by FredrikOseberg** [comment]
No problem. I didn't receive it yet. Did you send the invite to the correct
user/address?

**Comment by FredrikOseberg** [comment]
> I shared an invite with you to the repository, thanks a lot for taking the time!

Alright. I've taken a look and the good news is that the issue is not related to this package. It seems your chat header is a paragraph that spans the entire height of the chatbot and is "overlaying" over a big part of your viewport: 

<img width="1726" alt="Skjermbilde 2021-02-03 kl  21 10 39" src="https://user-images.githubusercontent.com/16081982/106803259-4d9f9980-6664-11eb-8e96-b588bc1d52e0.png">

Your buttons are placed underneath this element which means that when you are trying to click them, you are actually clicking on the paragraph element. May I suggest you implement a custom header component if you need to change the chatbot header? 

In the config: 

```
  customComponents: {
     // Replaces the default header
    header: () => <div style={{ backgroundColor: 'red', padding: "5px", borderRadius: "3px" }}>This is the header</div>
  },
```

Let me know if that helps you out :)

**Comment by Stijnvhd** [comment]
Hi, thanks for having a look! I adapted the code but I am afraid the problem persists.

**Comment by FredrikOseberg** [comment]
If you remove your paragraph with the class of "chat_titel", the problem
persists? I could press the buttons just fine on my end.

**Comment by Stijnvhd** [comment]
Found the problem, was on a different page something similar. Thanks a lot for your time and feedback, and thanks a lot for the package in general!
