### ISSUE TITLE
Is this library ssr compliant ?

### ISSUE THREAD

**Issue by Tanmayp11** [FredrikOseberg/react-chatbot-kit#22]
Can we compile application using this library and serve in via express application ?

**Comment by Tanmayp11** [comment]
ReferenceError: document is not defined
    at u (C:\Documents\reference\testreact\test_bot\node_modules\react-chatbot-kit\build\index.js:1:6198)

How to use this library with existing applications rendered server side ?

**Comment by FredrikOseberg** [comment]
> @FredrikOseberg
> ReferenceError: document is not defined
> at u (C:\Documents\reference\testreact\test_bot\node_modules\react-chatbot-kit\build\index.js:1:6198)
> 
> How to use this library with existing applications rendered server side ?
> 
> Using Express for ssr

Thanks. I'll look into it.

**Comment by Tanmayp11** [comment]
I think by code splitting my project using webpack can resolve things, just figuring out how should I proceed.

**Comment by FredrikOseberg** [comment]
> I think by code splitting my project using webpack can resolve things, just figuring out how should I proceed.

That could work. I'm looking into creating a build target for the server specifying node as the target. I'll let you know when I progress on this.

**Comment by FredrikOseberg** [comment]
@Tanmayp11 I build a new version: 1.1.2. It should take of this issue. I was successfully able to use the package using ReactDOM.hydrate and an express application. Thanks for bringing this to my attention.
