### ISSUE TITLE
Close button and Minimise on Outside click

### ISSUE THREAD

**Issue by atishwarchand** [FredrikOseberg/react-chatbot-kit#25]
Hello Everyone

Need help. Is there any way to Place a minimize or close button on the header [rightside]?
As in screenshot?
<img width="362" alt="Screenshot 2021-02-17 at 3 11 48 PM" src="https://user-images.githubusercontent.com/61366632/108151198-ae35d880-7132-11eb-9017-34b643ef32ed.png">

AND a way to minimize the chatbot popover on outside click. [Clicking anywhere outside in the window]

**Comment by FredrikOseberg** [comment]
Yes. You can create your own custom header and include a button: 

```
// Export a function that returns the config
const getConfig = (onClick) => {
  const config = {
    botName: "myBot",
    initialMessages: [
      createChatBotMessage(`Hi I'm ${botName}`),
    ],
    customComponents: {
       // Replaces the default header
      header: () => <div style={{ backgroundColor: 'red', padding: "5px", borderRadius: "3px" }}>This is the header <button onClick={close}>Close</button></div>
    },
  };
  }
}

export default getConfig

// in App.js

const App = () => {
     const [show, toggleShow] = useState(false)
     
     useEffect(() => {
          const handleOutsideClick = (e) => {
            // simple implementation, should be made more robust.
            if (e.currentTarget.classList.includes("react-chatbot-kit") {
                  toggleShow(false)
            }
       }
     
        window.addEventListener("click", handleOutsideClick)
        
        return () => {
             window.removeEventListener("click", handleOutsideClick)
        }
     }, [])
     


     const onClick = () => toggleShow(false)
    
     
     return show ? <Chatbot messageParser={messageParser} actionProvider={actionProvider} config={getConfig(onClick)} /> : null;
}
```

**Comment by atishwarchand** [comment]
Hi @FredrikOseberg for some reasons I cannot implement the "click outside and close chat" thing. Heres my codes.. If you can see and help. 

```
import React, { useState } from 'react';
import { Row, Col } from 'reactstrap';
import Tooltip from 'react-tooltip-lite';
import Chatbot from 'react-chatbot-kit';
import '../styles/chatbot.scss';
import config from "chatbot/config";
import MessageParser from "chatbot/MessageParser";
import ActionProvider from "chatbot/ActionProvider";
import { Icon } from '@iconify/react';
import robotIcon from '@iconify-icons/mdi/wechat';

const ChatBot = () => {

  const [showBot, toggleBot] = useState(false);

  return (
    <Row>
      <Col xs={10}>
        <div className="app-chatbot-container">
          <div style={{ maxWidth: "500px" }}>
            {showBot && (
              <Chatbot
                config={config}
                botAvator={<Icon icon={robotIcon} className="app-chatbot-button-icon" style={{ fontSize: '40', color: 'white' }} />}
                actionProvider={ActionProvider}
                messageParser={MessageParser}
                headerText={<text>Ask chatbot &nbsp;<a style={{ color: "white", fontWeight: "bold", background: "#0a5e9c", borderRadius: "0px" }} href="#" onClick={() => toggleBot((prev) => !prev)}>x</a></text>}
                placeholderText={"Type something..."}
                close="true"
              />
            )}
            <button className="app-chatbot-button" onClick={() => toggleBot((prev) => !prev)}>
              <Tooltip
                className="app-chatbox"
                content={(
                  <div>
                    <div className="app-chatbox">
                      Chat with Sara <br />
                    </div>
                  </div>
                )}
                direction="left"
                forceDirection
              >
                <div>
                  {<Icon icon={robotIcon} className="app-chatbot-button-icon" style={{ fontSize: '40', color: 'white' }} />}
                </div>
              </Tooltip>
            </button>
          </div>
        </div>
      </Col>
    </Row>
  );
};

export default ChatBot;
```

**Comment by FredrikOseberg** [comment]
> Hi @FredrikOseberg for some reasons I cannot implement the "click outside and close chat" thing. Heres my codes.. If you can see and help.
> 
> ```
> import React, { useState } from 'react';
> import { Row, Col } from 'reactstrap';
> import Tooltip from 'react-tooltip-lite';
> import Chatbot from 'react-chatbot-kit';
> import '../styles/chatbot.scss';
> import config from "chatbot/config";
> import MessageParser from "chatbot/MessageParser";
> import ActionProvider from "chatbot/ActionProvider";
> import { Icon } from '@iconify/react';
> import robotIcon from '@iconify-icons/mdi/wechat';
> 
> const ChatBot = () => {
> 
>   const [showBot, toggleBot] = useState(false);
> 
>   return (
>     <Row>
>       <Col xs={10}>
>         <div className="app-chatbot-container">
>           <div style={{ maxWidth: "500px" }}>
>             {showBot && (
>               <Chatbot
>                 config={config}
>                 botAvator={<Icon icon={robotIcon} className="app-chatbot-button-icon" style={{ fontSize: '40', color: 'white' }} />}
>                 actionProvider={ActionProvider}
>                 messageParser={MessageParser}
>                 headerText={<text>Ask chatbot &nbsp;<a style={{ color: "white", fontWeight: "bold", background: "#0a5e9c", borderRadius: "0px" }} href="#" onClick={() => toggleBot((prev) => !prev)}>x</a></text>}
>                 placeholderText={"Type something..."}
>                 close="true"
>               />
>             )}
>             <button className="app-chatbot-button" onClick={() => toggleBot((prev) => !prev)}>
>               <Tooltip
>                 className="app-chatbox"
>                 content={(
>                   <div>
>                     <div className="app-chatbox">
>                       Chat with Sara <br />
>                     </div>
>                   </div>
>                 )}
>                 direction="left"
>                 forceDirection
>               >
>                 <div>
>                   {<Icon icon={robotIcon} className="app-chatbot-button-icon" style={{ fontSize: '40', color: 'white' }} />}
>                 </div>
>               </Tooltip>
>             </button>
>           </div>
>         </div>
>       </Col>
>     </Row>
>   );
> };
> 
> export default ChatBot;
> ```

Hey, did you forget to add this part? 
```
     useEffect(() => {
          const handleOutsideClick = (e) => {
            // simple implementation, should be made more robust.
            if (!e.currentTarget.classList.includes("react-chatbot-kit") {
                  toggleShow(false)
            }
       }
     
        window.addEventListener("click", handleOutsideClick)
        
        return () => {
             window.removeEventListener("click", handleOutsideClick)
        }
     }, [])
```

**Comment by atishwarchand** [comment]
@FredrikOseberg I did that bro, but some sort of error occurred. That's why I sent the codes so that you could help directly in the code...

**Comment by FredrikOseberg** [comment]
> @FredrikOseberg I did that bro, but some sort of error occurred. That's why I sent the codes so that you could help directly in the code...
> 
> My site broke literally....

I'm sorry to hear that, but it's really hard to debug something like that without more information. And it's most likely a common javascript error, and not related to this package :) 

I can't see the section I mentioned in your code, and it was only an example. If you copy pasted it into App.js it won't work. Try removing it and adding this instead: 
```
import React, { useEffect, useState } from 'react';

const ChatBot = () => {
     const [showBot, toggleBot] = useState(false);

     useEffect(() => {
          const handleOutsideClick = (e) => {
            // simple implementation, should be made more robust.
            if (!e.currentTarget.classList.includes("react-chatbot-kit") {
                  toggleBot(false)
            }
       }
     
        window.addEventListener("click", handleOutsideClick)
        
        return () => {
             window.removeEventListener("click", handleOutsideClick)
        }
     }, [])

  return (
    <Row>
      <Col xs={10}>
        <div className="app-chatbot-container">
          <div style={{ maxWidth: "500px" }}>
            {showBot && (
              <Chatbot
                config={config}
                botAvator={<Icon icon={robotIcon} className="app-chatbot-button-icon" style={{ fontSize: '40', color: 'white' }} />}
                actionProvider={ActionProvider}
                messageParser={MessageParser}
                headerText={<text>Ask chatbot &nbsp;<a style={{ color: "white", fontWeight: "bold", background: "#0a5e9c", borderRadius: "0px" }} href="#" onClick={() => toggleBot((prev) => !prev)}>x</a></text>}
                placeholderText={"Type something..."}
                close="true"
              />
            )}
            <button className="app-chatbot-button" onClick={() => toggleBot((prev) => !prev)}>
              <Tooltip
                className="app-chatbox"
                content={(
                  <div>
                    <div className="app-chatbox">
                      Chat with Sara <br />
                    </div>
                  </div>
                )}
                direction="left"
                forceDirection
              >
                <div>
                  {<Icon icon={robotIcon} className="app-chatbot-button-icon" style={{ fontSize: '40', color: 'white' }} />}
                </div>
              </Tooltip>
            </button>
          </div>
        </div>
      </Col>
    </Row>
  );
};

export default ChatBot;
```

**Comment by atishwarchand** [comment]
@FredrikOseberg tried this and other ways, but im not able to get it working. 

errors are below..

![Screenshot 2021-02-18 at 10 18 24 AM](https://user-images.githubusercontent.com/61366632/108275416-cfe69c80-71d2-11eb-9503-baad1b19ab37.png)
![Screenshot 2021-02-18 at 10 18 36 AM](https://user-images.githubusercontent.com/61366632/108275426-d412ba00-71d2-11eb-87d4-5f73b9067843.png)

Do help if your know whats the issue.

**Comment by FredrikOseberg** [comment]
Yes. My bad. Swap out .includes with .contains

Includes only works on strings.

ons. 17. feb. 2021 kl. 23:20 skrev Atishwar Chand <notifications@github.com

**Comment by atishwarchand** [comment]
@FredrikOseberg I had already tried that but still no luck....

nevertheless the error again..

<img width="742" alt="Screenshot 2021-02-18 at 10 30 32 AM" src="https://user-images.githubusercontent.com/61366632/108276497-69627e00-71d4-11eb-9534-ee4020c14ad5.png">

**Comment by FredrikOseberg** [comment]
Can you post me the output of the following? 
```
console.log(e.currentTarget)
console.log(e)
```

**Comment by atishwarchand** [comment]
Attached as asked.

<img width="772" alt="Screenshot 2021-02-18 at 10 45 24 AM" src="https://user-images.githubusercontent.com/61366632/108277784-7c764d80-71d6-11eb-8e4f-6d8428998920.png">

**Comment by FredrikOseberg** [comment]
> Attached as asked.
> 
> <img alt="Screenshot 2021-02-18 at 10 45 24 AM" width="772" src="https://user-images.githubusercontent.com/61366632/108277784-7c764d80-71d6-11eb-8e4f-6d8428998920.png">

Do you have your code on github? I need to take a closer look.

**Comment by proton029** [comment]
@atishwarchand is your issue resolved? if so can you share how .

**Comment by proton029** [comment]
i was able to solve using  useContext and useReducer.

**Comment by bagdadstyle** [comment]
> @atishwarchand is your issue resolved? if so can you share how .

bro, can you show me  your code?  i can't resolve this problem
