### ISSUE TITLE
Nav Bar Menu

### ISSUE THREAD

**Issue by dtcyad1** [FredrikOseberg/react-chatbot-kit#26]
Hi Fredrik,

I am implementing a nav header with icons and a dropdown menu. I have gotten the menu to work - but now i need some help integrating that with the chatbot kit. I have 2 solns in mind - but could not get either of them to work. The first soln was to pass the actionProvider to my Functional Menu Component. However, I could not find a way to do that. Currently, my config looks like this:

customComponents: {
  header: () => 
  <div className="react-chatbot-kit-chat-header">
    <NavHeader />
        </div>
},

The second approach i thought was to somehow programatically fire the submit button - something like this:

document.getElementsByClassName('react-chatbot-kit-chat-input').value = 'hello';
document.getElementsByClassName("react-chatbot-kit-chat-input-form")[0].submit();

and then everything should work normally. But, what happens is the whole page is getting refreshed instead of sending a message with the value of "hello".

This is the starting code for my nav component:

function NavHeader() {
  
  return (
    <Navbar>
      <NavItem icon={<PlusIcon />} />
      <NavItem icon={<BellIcon />} />
      <NavItem icon={<MessengerIcon />} />

      <NavItem icon={<CaretIcon />}>
        <DropdownMenu></DropdownMenu>
      </NavItem>
    </Navbar>
  );
}
![Screen Shot 2021-02-17 at 10 46 29 AM](https://user-images.githubusercontent.com/11274728/108229593-f1318500-710d-11eb-8bab-a47b1bb33984.png)

Below is how my nav header is looking..

![Screen Shot 2021-02-17 at 10 46 29 AM](https://user-images.githubusercontent.com/11274728/108229096-7c5e4b00-710d-11eb-856f-9e822dbcd1e8.png)

Thanks

**Comment by dtcyad1** [comment]
Oops - the config code did not make it - attaching it again:

customComponents: {
  header: () => 
  <div className="react-chatbot-kit-chat-header">
    <NavHeader />
        </div>
},

**Comment by dtcyad1** [comment]
Oops - the code did not make it - attaching again
![Screen Shot 2021-02-17 at 10 55 50 AM](https://user-images.githubusercontent.com/11274728/108230409-c1cf4800-710e-11eb-99d5-9e25fb14014d.png)


![Screen Shot 2021-02-17 at 10 56 38 AM](https://user-images.githubusercontent.com/11274728/108230480-d4e21800-710e-11eb-9f50-46bc2a6d55fa.png)

**Comment by FredrikOseberg** [comment]
Looking into it.

**Comment by dtcyad1** [comment]
Hi Fredrik,

were you able to figure out a way? Really appreciate you looking into this.

Thanks

**Comment by FredrikOseberg** [comment]
> Hi Fredrik,
> 
> were you able to figure out a way? Really appreciate you looking into this.
> 
> Thanks

Yeah. I'm going to inject the actionProvider into the header function when it's called. That way you should be able to access the actionprovider in your custom header.

**Comment by dtcyad1** [comment]
Awesome - Thanks.

**Comment by FredrikOseberg** [comment]
> Awesome - Thanks.

If you get the latest version (1.1.14) and amend your config like this: 

```
import { createChatBotMessage } from "react-chatbot-kit";

import Header from "./header";

const config = {
  initialMessages: [createChatBotMessage(`Hello world`)],
  customComponents: {
    header: (props) => <Header {...props} />,
  },
};

export default config;

```

You should now have access to the actionProvider.

**Comment by dtcyad1** [comment]
So i got the latest code - i can see that you are now passing in the action header. But i am unable to get the actionProvider. This is how I am using it:

config.js:
customComponents: {
  header: (props) => <NavHeader {...props} />,
}, 

NavHeader.js:
function NavHeader({actionProvider}) {
  console.log("Header::" + actionProvider);
  return (
....Header render code
);
}

But in the console, this is what i see printed in the console:

Header::undefined

**Comment by FredrikOseberg** [comment]
> So i got the latest code - i can see that you are now passing in the action header. But i am unable to get the actionProvider. This is how I am using it:
> 
> config.js:
> customComponents: {
> header: (props) => <NavHeader {...props} />,
> },
> 
> NavHeader.js:
> function NavHeader({actionProvider}) {
> console.log("Header::" + actionProvider);
> return (
> ....Header render code
> );
> }
> 
> But in the console, this is what i see printed in the console:
> 
> Header::undefined

Try augmenting your config like this: 
```
const config = {
  initialMessages: [createChatBotMessage(`Hello world`)],
  customComponents: {
    header: (actionProvider) => <Header actionProvider={actionProvider} />,
  },
};
```

**Comment by dtcyad1** [comment]
Hi Fredrik,

This is awesome!! Works like a charm. Really appreciate this fast turnaround!! You can close this case.

Thanks

**Comment by FredrikOseberg** [comment]
> Hi Fredrik,
> 
> This is awesome!! Works like a charm. Really appreciate this fast turnaround!! You can close this case.
> 
> Thanks

Perfect. Thanks for reporting :)

**Comment by iammmk** [comment]
> Hi Fredrik,
> 
> This is awesome!! Works like a charm. Really appreciate this fast turnaround!! You can close this case.
> 
> Thanks

Hi @dtcyad1 
I can see that actionProvider is giving the ActionProvider function when log this in console. If this is correct, then how to use this actionProvider. Can you please provide the code.

Thanks
