### ISSUE TITLE
Create User Chat Message Programatically

### ISSUE THREAD

**Issue by dtcyad1** [FredrikOseberg/react-chatbot-kit#30]
Hi Fredrik,

Is it possible to create a User Chat Message? For example, in your example with learning options, you create a couple of buttons. Instead of firing the action directly, i want to submit that as a user message. So if the user clicked on the button called "JavaScript", then i want the user message to show as "JavaScript" in the chatbot - which can then be processed by the Message Parser in the normal way (and call the required action).

Thanks

**Comment by dtcyad1** [comment]
Hi Fredrik,

Got it to work in the ActionProvider. I was using an older version of the AP where the createClientMessage was not being passed in my constructor. You may close this issue.

Thanks

**Comment by alanmrochadeveloper** [comment]
Same issue. 
![image](https://user-images.githubusercontent.com/54696320/126333744-0e718420-b8ad-424c-bf67-1d899e7c480f.png)
![image](https://user-images.githubusercontent.com/54696320/126333855-83192659-15bf-4d00-8787-1c420711d939.png)
this.createChatBotMessage(message)
but this.createClientMessage(message) doesn't
Is there a reason why?  It says createClientMessage is not a function, using typeof it says it is undefined!
PS: I'm using typescript, most of the types are "any" for tests purposes!

**Comment by alanmrochadeveloper** [comment]
My mistake. Well, just fixed it.
![image](https://user-images.githubusercontent.com/54696320/126386776-8bee2a7e-07c8-4212-814a-e14d83b8d90a.png)
I was passing a 3rd constructor parameter as "setStep" in place of "createClientMessage, and the 4th parameter is undefined, so I fixed it. Removing the 4th parameter placing it as

**Comment by vahidsavabieh** [comment]
My ActionProvider is functional, but I cannot have a constructor . import createClientMessage from library . When I use createClientMessage  show the user message, it does not parse properly.
