### ISSUE TITLE
Infinite loop when sending messages too fast

### ISSUE THREAD

**Issue by dakicnikola** [FredrikOseberg/react-chatbot-kit#32]
If user types 4 or more messages too fast, bot bumps into an infinite loop answering on all of the questions all the time.
It is reproducible on DocsBot too.

Let me show you what i mean, there is screen recording of DocsBot (and a .gif image made of recording)
https://user-images.githubusercontent.com/52914678/110318164-72917e80-800d-11eb-9213-2523b8e0a04e.mov

![Screen Recording 2021-03-08 at 12 53 50](https://user-images.githubusercontent.com/52914678/110334697-54367d80-8023-11eb-8c77-c0944f90948b.gif)

**Comment by FredrikOseberg** [comment]
> questions

Thanks, that's a nasty a bug. I'll investigate.

**Comment by FredrikOseberg** [comment]
Thanks a lot for the report, this should be fixed in 1.1.17.
