### ISSUE TITLE
How to add image on userchat

### ISSUE THREAD

**Issue by arissaraZ** [FredrikOseberg/react-chatbot-kit#48]
`const clientMessage = props.actionProvider.createClientMesssage(image)`
`props.actionProvider.setClientMessage(clientMessage)`

I want to change from message to image. Help me please

![image](https://user-images.githubusercontent.com/80831428/113346752-755a6780-935e-11eb-8a0c-c5279a361bb4.png)

**Comment by FredrikOseberg** [comment]
Hello. Please refrain from opening duplicate issues.
