### ISSUE TITLE
When someone click on a button i want to display The text in the button as a client message . 

### ISSUE THREAD

**Issue by 88hichem88** [FredrikOseberg/react-chatbot-kit#5]
In the action provider 
Please add a new function similar to 
this.createChatBotMessage("");

That allow to create a client message 

this.createClientMessage("");

To display the text in the button clicked on So the client feel like he said something ( when he clicked on the button )

**Comment by FredrikOseberg** [comment]
I'll look into it. Meanwhile, you can create this method yourself.. You just need to add a message to the messages array with the type "user".

In the actionprovider: 
`createClientMesssage = (message) => {
       const clientMessage = {
              messsage: message,
              type: "user", 
              id: somethingUnique
      }

      this.setState(prevState => ({
           ...prevState, messages: [...prevState.messages, clientMessage]
      }))
}`

**Comment by 88hichem88** [comment]
Thanks a lot. 
I'm already developing my first bot with the chat-bot-kit and so far it's amazing. 
Wish you great success.

**Comment by 88hichem88** [comment]
For anyone who's gonna use the "createClientMesssage"  function ( Mr.FredrikOseberg  spelled  meSSSage wrong ) it's message with only two "ss"  ( I hope no one spend 2 hr trying to figure out why the message is always empty XD ) 

createClientMesssage = ( message) => {
       const clientMessage = {
              message: message,
              type: "user", 
              id: somethingUnique
      }

     return  clientMessage
}
