### ISSUE TITLE
how to handle empty message with out rendering 

### ISSUE THREAD

**Issue by skmainwal** [FredrikOseberg/react-chatbot-kit#52]
Hello Fredrik,thanks for your chatbot-kit .it helped me a lot .
I am making a chatBot with a chatbot kit but I'm facing a problem that when I click on enter without message then chatbot kit render the empty message .I want to stop this one . here is the pic of issue. How can I remove this empty message .

![image](https://user-images.githubusercontent.com/61382724/116372413-03285600-a82a-11eb-9d4b-cf73619619ac.png)

**Comment by FredrikOseberg** [comment]
> Hello Fredrik,thanks for your chatbot-kit .it helped me a lot .
> I am making a chatBot with a chatbot kit but I'm facing a problem that when I click on enter without message then chatbot kit render the empty message .I want to stop this one . here is the pic of issue. How can I remove this empty message .
> 
> ![image](https://user-images.githubusercontent.com/61382724/116372413-03285600-a82a-11eb-9d4b-cf73619619ac.png)

Hi there! 

You can pass a function to the chatbot to check if the client message is valid or not: 

```
const validator = (input) => {
     if (input.length > 3) return true;
     return false
}

<Chatbot messageParser={messageParser} config={config) actionProvider={actionProvider} validator={validator} />
```

**Comment by skmainwal** [comment]
thanks Fredrik , it helped me .
