### ISSUE TITLE
Set header background image

### ISSUE THREAD

**Issue by junaidahmed361** [FredrikOseberg/react-chatbot-kit#55]
I'm trying to change the header properties in config.js to allow for a background image. However neither the div element with a backgroundImage property applied nor an img tag with src defined works. I've even tried editing the css code for .App-header to allow the background-image, but still nothing. And for that matter, within the div element, I can't place an img tag to hold another small logo image in the header. How can I go about doing these things, if any are possible?

**Comment by NizarAffess** [comment]
In your src folder hide the header the follwoing way: in 'App.css'
`.react-chatbot-kit-chat-header {
  display: none !important;
}`
Then create your own header component and implement it. I created mine and it looks pretty similar to Messenger header.
