### ISSUE TITLE
How to avoid creating new message when user enters null value?

### ISSUE THREAD

**Issue by VeenaMalali13** [FredrikOseberg/react-chatbot-kit#59]
When user types nothing in input and hit enter/submit button, it should not create new user message with createChatBotMesage() method. Rather it should not accept null value. Trying to do this, but not getting solution.

**Comment by FredrikOseberg** [comment]
> When user types nothing in input and hit enter/submit button, it should not create new user message with createChatBotMesage() method. Rather it should not accept null value. Trying to do this, but not getting solution.


Hi there! 

You can pass a function to the chatbot to check if the client message is valid or not: 

```
const validator = (input) => {
     if (input.length > 3) return true;
     return false
}

<Chatbot messageParser={messageParser} config={config) actionProvider={actionProvider} validator={validator} />
```

**Comment by VeenaMalali13** [comment]
Thank You Fredrik...This helped me
