### ISSUE TITLE
How to remove and update prefix 'conversation with' with header title

### ISSUE THREAD

**Issue by vijay-kumar-singh** [FredrikOseberg/react-chatbot-kit#64]
Hi,

Currently prefix 'conversation with' being added with botName variable. 
Could you please suggest how to remove this prefix. I would like to add/remove my own prefix word.

Thank you.

**Comment by FredrikOseberg** [comment]
Hi. You can create a custom header component that will replace the default.
Follow the link in documentation to find all configurable properties to see
how it can be done.

tir. 15. jun. 2021 kl. 00:18 skrev Vijay Singh ***@***.***>:

**Comment by vijay-kumar-singh** [comment]
Resolved with adding custom header
