### ISSUE TITLE
Disable send button on no input from user?

### ISSUE THREAD

**Issue by pavansai2299** [FredrikOseberg/react-chatbot-kit#69]
Hi, thanks for this amazing package.

Is there any way to disable send button on no user input or null input from user?

please help me in this

**Comment by pavansai2299** [comment]
Found the solution. Thanks

**Comment by VeenaMalali13** [comment]
Hi,
Can you please share the solution?

**Comment by pavansai2299** [comment]
Hi,
You can pass the validator function like below as props to chatbot component. you can filter user input for null or even you can restrict the user to specific length according to the logic. 

The below method prevents sending any user message when input is null.

const validator = (input) => {
     if (input.length > 0) return true;
     return false
}

<Chatbot messageParser={messageParser} config={config) actionProvider={actionProvider} validator={validator} />

**Comment by VeenaMalali13** [comment]
Yes validator function I have used already. I thought you are actually disabling send button and enabling it only when user enters any value.
Thanks
