### ISSUE TITLE
Can we make the static text "Conversation with" in the header as optional? 

### ISSUE THREAD

**Issue by arjunbaiswar** [FredrikOseberg/react-chatbot-kit#7]
I checked within the module and the text is non-configurable i.e. static. I really liked the framework and it suits very well in the majority of use cases. One additional option I wished was if there could be a way to configure the whole header instead of just changing the Bot name. 
Thank you for your contribution! 

![image](https://user-images.githubusercontent.com/58863333/93024294-fe07f500-f612-11ea-8964-c54e4d2ff29e.png)

**Comment by FredrikOseberg** [comment]
Totally agree with you here. I'll put that in the pipeline.

**Comment by FredrikOseberg** [comment]
#8 

Adds support for:
* header property in customComponents, allowing you to completely swap out the header.
* headerText as props to the chatbot, swapping out the text.
* placeholderText as props to the chatbot, swapping out the placeholder text

Examples:

`
// In config
customComponents: {
     header: () => <div>My new header</div>
}

// Props usage
<Chatbot headerText="New header text" placeholderText="new placeholder text" config={config} messageParser={messageParser} actionProvider={actionProvider} />
`

**Comment by arjunbaiswar** [comment]
Thanks a lot, @FredrikOseberg for your quick response & action.
