### ISSUE TITLE
Getting error "this.createChatBotMessage is not a function" in action provider

### ISSUE THREAD

**Issue by VeenaMalali13** [FredrikOseberg/react-chatbot-kit#73]
I have written ActionProvider as react component which returns nothing

class ActionProvider extends React.Component{

    constructor(createChatBotMessage, setStateFunc, createClientMessage) {
      super(createChatBotMessage, setStateFunc, createClientMessage);

          this.createChatBotMessage = createChatBotMessage;
          this.createClientMessage = createClientMessage;
          this.setState = setStateFunc;
  }
  
  componentDidMount(){
    
    ------Trying to access this object here------
    
        setInterval(() => {
                    
            --fetch call--
            if(res.data.IdleTime == 5){
                  msg = this.createChatBotMessage( "Are you still with me?");
                  this.updateChatbotState(msg);
            }    
        },60000)    
  }
      render(){
        return(<></>)
      }
}
export default ActionProvider;

I am getting error in componentDidMount "this.createChatBotMessage is not a function"
![createChatBotMessage_issue](https://user-images.githubusercontent.com/46866103/125964555-ed5ed002-b4e6-4bda-bc8f-797477490521.png)

**Comment by FredrikOseberg** [comment]
Action provider is a regular JS class and does not implement
componentDidMount or any other React interface. You need to adhere to js
class rules.

fre. 16. jul. 2021 kl. 16:37 skrev VeenaMalali13 ***@***.***>:

**Comment by VeenaMalali13** [comment]
Thanks Fredrik..
