### ISSUE TITLE
How to pass params to widget?

### ISSUE THREAD

**Issue by zilinailee** [FredrikOseberg/react-chatbot-kit#88]
I have a widget that will open a new tab upon click to google search the word user input in the chatbot message field but I can’t seem to find a way to pass the chatbot message as a param to the widget function

**Comment by greendinosaur** [comment]
I know this is closed but if anyone else has a similar issue about passing data to a widget then I found you can use the payload  as in the ActionProvider class
```
const botMessage = createChatBotMessage(" ", {
      widget: MyWidget,
      payload: result.content,
    });
```

you can then access this in the widget
```
const MyWidget = (message) => {
  return (
    <div >
      {message.payload}
    </div>
  );
};
```
