### ISSUE TITLE
Not able to view chatbot properly in reactjs using vs code

### ISSUE THREAD

**Issue by richas0719** [FredrikOseberg/react-chatbot-kit#91]
![16125B25-36C8-43AB-B8E8-952483843ABB](https://user-images.githubusercontent.com/72738297/141272974-5ff04a57-20c1-4add-bd07-0fb751a2ff1d.jpeg)
This is how I am able to render the chatbot as of now on my mac using vscode. Can you help out as to why am I not able to view the chatbot as you have shown? It would be great if you could provide a solution to this issue!

**Comment by FredrikOseberg** [comment]
Hi there! This package has been updated to version 2.0, which means that you now need to include an external stylesheet as stated explicitly in the [docs here](https://fredrikoseberg.github.io/react-chatbot-kit-docs/docs/) 

Adding this stylesheet in your imports should take care of your issue! Good day :)

**Comment by richas0719** [comment]
Thanks alot. This helped fix my issue! Good day to you too :)
