### ISSUE TITLE
typeerror t is not a constructor

### ISSUE THREAD

**Issue by GuerreroDLaCruz** [FredrikOseberg/react-chatbot-kit#97]
hey man i simply tried to used your chat bot, but it gives me this error prior its launch, seems the error is inside its modules/react-chat-bot/build/index

**Comment by FredrikOseberg** [comment]
Ok. Seems weird. Are you absolutely sure that your action provider and message parser are exported classes that you can instantiate?

**Comment by SortedIvan** [comment]
I am having the exact same issue and I don't know whats causing it. Everything is exported correctly and set-up as in your tutorial.

**Comment by FredrikOseberg** [comment]
Can you please provide a reproducable example?

søn. 19. des. 2021 kl. 02:15 skrev Ivan Ovcharov ***@***.***>:

**Comment by Pinni05** [comment]
Hi I am getting the same error. Any solution?

**Comment by FredrikOseberg** [comment]
> Hi I am getting the same error. Any solution?

https://codesandbox.io/s/sparkling-paper-0ewh7

Here is a working example. Apparently there is a mistake in the docs when it comes to the message parser, you need to export it. Add the line `export default MessageParser` at the bottom of the file.
